#!/bin/ash
#################################################################################
CCIO OpenWRT Script to enable LuCi WebUI on WAN Interface

WARNING:
        This is NOT a recommended configuration for security.
        Please only use this rule if your gateway is on a trusted network.


#################################################################################
# Backup Firewall Config
cp /etc/config/firewall /root/bak/firewall.original


#################################################################################
# Load LuCi WAN Firewall rule
echo "
config redirect
        option target 'DNAT'
        option src 'wan'
        option dest 'lan'
        option proto 'tcp udp'
        option src_dport '80'
        option dest_ip '192.168.1.1'
        option name 'openwrt-webui'
        option dest_port '80'
" >>/etc/config/firewall


#################################################################################
# Reload Firewall 
/etc/init.d/firewall reload 2>/dev/null 1>/dev/null


#################################################################################
# Disable script
rm /usr/bin/enable-webui-on-wan
mv /root/enable-webui-on-wan /root/bak/


#################################################################################
# Detect WAN IP
sleep 5 && wan_IP=$(ip address show eth0 | awk -F'[ /]' '/inet /{print $6}')


#################################################################################
# Echo Disclaimer & URL to Screen
echo "
            ~~~~~~~~~~~~~~~~~~~~~
WARNING: 
    This is not a secure configuration
    Public access to port 80 is potentially dangerous
    Only use this configuration in trusted networks


  OpenWRT Webui Now accessible at:

  http://${wan_IP}:80/cgi-bin/luci/


            ~~~~~~~~~~~~~~~~~~~~~
"
